import 'package:flutter_tech_commerce_ui/models/product.dart';

class ProductService {
  static List<Category> getCategories() {
    return [
      Category(
        id: 'electronics',
        name: 'Electronics',
        icon: 'smartphone',
        image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=400&h=300&fit=crop',
        description: 'Latest gadgets and technology',
        productCount: 156,
      ),
      Category(
        id: 'fashion',
        name: 'Fashion',
        icon: 'shirt',
        image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400&h=300&fit=crop',
        description: 'Trendy clothing and accessories',
        productCount: 243,
      ),
      Category(
        id: 'home',
        name: 'Home & Garden',
        icon: 'home',
        image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&h=300&fit=crop',
        description: 'Beautiful home decor and furniture',
        productCount: 189,
      ),
      Category(
        id: 'sports',
        name: 'Sports',
        icon: 'dumbbell',
        image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop',
        description: 'Fitness and outdoor equipment',
        productCount: 134,
      ),
      Category(
        id: 'beauty',
        name: 'Beauty',
        icon: 'cosmetics',
        image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=300&fit=crop',
        description: 'Skincare and beauty products',
        productCount: 98,
      ),
      Category(
        id: 'books',
        name: 'Books',
        icon: 'book',
        image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=300&fit=crop',
        description: 'Books and educational materials',
        productCount: 276,
      ),
      Category(
        id: 'toys',
        name: 'Toys & Games',
        icon: 'game-controller',
        image: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=400&h=300&fit=crop',
        description: 'Fun toys and games for all ages',
        productCount: 167,
      ),
      Category(
        id: 'automotive',
        name: 'Automotive',
        icon: 'car',
        image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400&h=300&fit=crop',
        description: 'Car accessories and parts',
        productCount: 92,
      ),
    ];
  }

  static List<Product> getAllProducts() {
    return [
      // Electronics
      Product(
        id: 'iphone15',
        name: 'iPhone 15 Pro',
        description: 'The most advanced iPhone with A17 Pro chip, titanium design, and pro camera system.',
        price: 999.0,
        originalPrice: 1099.0,
        category: 'electronics',
        brand: 'Apple',
        images: [
          'https://picsum.photos/600/600?random=10',
          'https://picsum.photos/600/600?random=11',
          'https://picsum.photos/600/600?random=12',
        ],
        rating: 4.8,
        reviewCount: 1247,
        colors: ['Natural Titanium', 'Blue Titanium', 'White Titanium', 'Black Titanium'],
        sizes: ['128GB', '256GB', '512GB', '1TB'],
        isInStock: true,
        isFeatured: true,
        isOnSale: true,
        discount: 9,
        material: 'Titanium',
        features: ['A17 Pro Chip', 'Pro Camera System', '6.1" Display', 'Face ID'],
      ),
      Product(
        id: 'samsung_s24',
        name: 'Samsung Galaxy S24 Ultra',
        description: 'Ultimate smartphone with S Pen, 200MP camera, and Galaxy AI features.',
        price: 1199.0,
        originalPrice: 1299.0,
        category: 'electronics',
        brand: 'Samsung',
        images: [
          'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&h=600&fit=crop',
          'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=600&h=600&fit=crop',
        ],
        rating: 4.7,
        reviewCount: 892,
        colors: ['Titanium Gray', 'Titanium Black', 'Titanium Violet', 'Titanium Yellow'],
        sizes: ['256GB', '512GB', '1TB'],
        isInStock: true,
        isFeatured: true,
        isOnSale: true,
        discount: 8,
        material: 'Titanium Frame',
        features: ['S Pen Included', '200MP Camera', 'Galaxy AI', '6.8" Display'],
      ),
      Product(
        id: 'macbook_air',
        name: 'MacBook Air M3',
        description: 'Supercharged by the M3 chip, featuring a stunning display and all-day battery life.',
        price: 1299.0,
        originalPrice: 1399.0,
        category: 'electronics',
        brand: 'Apple',
        images: [
          'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&h=600&fit=crop',
          'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=600&h=600&fit=crop',
        ],
        rating: 4.9,
        reviewCount: 756,
        colors: ['Space Gray', 'Silver', 'Gold', 'Midnight'],
        sizes: ['256GB', '512GB', '1TB', '2TB'],
        isInStock: true,
        isFeatured: true,
        isOnSale: true,
        discount: 7,
        material: 'Aluminum',
        features: ['M3 Chip', '13.6" Liquid Retina', 'Touch ID', '18-hour Battery'],
      ),
      Product(
        id: 'sony_headphones',
        name: 'Sony WH-1000XM5',
        description: 'Industry-leading noise canceling headphones with exceptional sound quality.',
        price: 349.0,
        originalPrice: 399.0,
        category: 'electronics',
        brand: 'Sony',
        images: [
          'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600&h=600&fit=crop',
          'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600&h=600&fit=crop&crop=entropy',
        ],
        rating: 4.6,
        reviewCount: 1534,
        colors: ['Black', 'Silver'],
        sizes: ['One Size'],
        isInStock: true,
        isFeatured: false,
        isOnSale: true,
        discount: 12,
        material: 'Premium Plastic',
        features: ['Noise Canceling', '30-hour Battery', 'Quick Charge', 'Touch Controls'],
      ),
      Product(
        id: 'ipad_pro',
        name: 'iPad Pro 12.9"',
        description: 'The ultimate iPad experience with M2 chip and Liquid Retina XDR display.',
        price: 1099.0,
        originalPrice: 1199.0,
        category: 'electronics',
        brand: 'Apple',
        images: [
          'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&h=600&fit=crop',
          'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&h=600&fit=crop&crop=top',
        ],
        rating: 4.8,
        reviewCount: 623,
        colors: ['Space Gray', 'Silver'],
        sizes: ['128GB', '256GB', '512GB', '1TB', '2TB'],
        isInStock: true,
        isFeatured: true,
        isOnSale: true,
        discount: 8,
        material: 'Aluminum',
        features: ['M2 Chip', 'Liquid Retina XDR', 'Apple Pencil Support', 'Face ID'],
      ),

      // Fashion
      Product(
        id: 'nike_sneakers',
        name: 'Nike Air Max 270',
        description: 'Comfortable lifestyle shoes with Max Air cushioning and modern design.',
        price: 150.0,
        originalPrice: 180.0,
        category: 'fashion',
        brand: 'Nike',
        images: [
          'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&h=600&fit=crop',
          'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&h=600&fit=crop',
        ],
        rating: 4.5,
        reviewCount: 2341,
        colors: ['White/Black', 'Black/Red', 'Blue/White', 'Pink/White'],
        sizes: ['7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '12'],
        isInStock: true,
        isFeatured: true,
        isOnSale: true,
        discount: 17,
        material: 'Mesh and Synthetic',
        features: ['Max Air Cushioning', 'Breathable Mesh', 'Rubber Outsole', 'Lightweight'],
      ),
      Product(
        id: 'denim_jacket',
        name: 'Classic Denim Jacket',
        description: 'Timeless denim jacket perfect for layering in any season.',
        price: 89.0,
        originalPrice: 120.0,
        category: 'fashion',
        brand: 'Levi\'s',
        images: [
          'https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?w=600&h=600&fit=crop',
          'https://images.unsplash.com/photo-1544441893-675973e31985?w=600&h=600&fit=crop',
        ],
        rating: 4.4,
        reviewCount: 876,
        colors: ['Light Blue', 'Dark Blue', 'Black', 'White'],
        sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        isInStock: true,
        isFeatured: false,
        isOnSale: true,
        discount: 26,
        material: '100% Cotton Denim',
        features: ['Classic Fit', 'Button Closure', 'Chest Pockets', 'Vintage Wash'],
      ),
      Product(
        id: 'leather_handbag',
        name: 'Luxury Leather Handbag',
        description: 'Elegant genuine leather handbag with spacious interior and premium finish.',
        price: 299.0,
        originalPrice: 399.0,
        category: 'fashion',
        brand: 'Coach',
        images: [
          'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&h=600&fit=crop',
          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=600&fit=crop',
        ],
        rating: 4.7,
        reviewCount: 445,
        colors: ['Black', 'Brown', 'Tan', 'Burgundy'],
        sizes: ['One Size'],
        isInStock: true,
        isFeatured: true,
        isOnSale: true,
        discount: 25,
        material: 'Genuine Leather',
        features: ['Multiple Compartments', 'Adjustable Strap', 'Gold Hardware', 'Dust Bag Included'],
      ),
      Product(
        id: 'cotton_tshirt',
        name: 'Premium Cotton T-Shirt',
        description: 'Soft, comfortable cotton t-shirt with perfect fit and premium quality.',
        price: 29.0,
        originalPrice: 39.0,
        category: 'fashion',
        brand: 'Uniqlo',
        images: [
          'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&h=600&fit=crop',
          'https://images.unsplash.com/photo-1503341338686-25301edf0055?w=600&h=600&fit=crop',
        ],
        rating: 4.3,
        reviewCount: 1823,
        colors: ['White', 'Black', 'Navy', 'Gray', 'Red', 'Green'],
        sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        isInStock: true,
        isFeatured: false,
        isOnSale: true,
        discount: 26,
        material: '100% Cotton',
        features: ['Pre-shrunk', 'Tagless', 'Machine Washable', 'Classic Fit'],
      ),
      Product(
        id: 'dress_watch',
        name: 'Classic Dress Watch',
        description: 'Elegant timepiece with leather strap and classic design for formal occasions.',
        price: 199.0,
        originalPrice: 249.0,
        category: 'fashion',
        brand: 'Citizen',
        images: [
          'https://images.unsplash.com/photo-1524805444073-b5d2b5516b1c?w=600&h=600&fit=crop',
          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop',
        ],
        rating: 4.6,
        reviewCount: 567,
        colors: ['Brown Leather', 'Black Leather', 'Silver Metal'],
        sizes: ['One Size'],
        isInStock: true,
        isFeatured: false,
        isOnSale: true,
        discount: 20,
        material: 'Stainless Steel',
        features: ['Water Resistant', 'Leather Strap', 'Analog Display', 'Date Function'],
      ),

      // Home & Garden
      Product(
        id: 'modern_sofa',
        name: 'Modern 3-Seat Sofa',
        description: 'Comfortable and stylish sofa perfect for any living room with premium upholstery.',
        price: 899.0,
        originalPrice: 1199.0,
        category: 'home',
        brand: 'West Elm',
        images: [
          'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=600&fit=crop',
          'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=600&fit=crop&crop=entropy',
        ],
        rating: 4.5,
        reviewCount: 234,
        colors: ['Gray', 'Navy', 'Beige', 'Charcoal'],
        sizes: ['3-Seat'],
        isInStock: true,
        isFeatured: true,
        isOnSale: true,
        discount: 25,
        material: 'Fabric Upholstery',
        features: ['Hardwood Frame', 'Removable Cushions', 'Easy Assembly', 'Stain Resistant'],
      ),
      Product(
        id: 'dining_table',
        name: 'Solid Wood Dining Table',
        description: 'Beautiful solid wood dining table that seats 6 people comfortably.',
        price: 649.0,
        originalPrice: 799.0,
        category: 'home',
        brand: 'IKEA',
        images: [
          'https://images.unsplash.com/photo-1549497538-303791108f95?w=600&h=600&fit=crop',
          'https://images.unsplash.com/photo-1549497538-303791108f95?w=600&h=600&fit=crop&crop=entropy',
        ],
        rating: 4.4,
        reviewCount: 456,
        colors: ['Natural Oak', 'Dark Walnut', 'White'],
        sizes: ['6-Person'],
        isInStock: true,
        isFeatured: false,
        isOnSale: true,
        discount: 19,
        material: 'Solid Wood',
        features: ['Seats 6', 'Easy Assembly', 'Durable Finish', 'Scratch Resistant'],
      ),
      Product(
        id: 'table_lamp',
        name: 'Modern Table Lamp',
        description: 'Sleek modern table lamp with adjustable brightness and contemporary design.',
        price: 79.0,
        originalPrice: 99.0,
        category: 'home',
        brand: 'Philips',
        images: [
          'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=600&fit=crop',
          'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=600&fit=crop&crop=entropy',
        ],
        rating: 4.2,
        reviewCount: 789,
        colors: ['White', 'Black', 'Brass'],
        sizes: ['One Size'],
        isInStock: true,
        isFeatured: false,
        isOnSale: true,
        discount: 20,
        material: 'Metal and Fabric',
        features: ['Dimmable', 'LED Compatible', 'Touch Switch', 'Modern Design'],
      ),
      Product(
        id: 'throw_pillows',
        name: 'Decorative Throw Pillows',
        description: 'Set of 2 luxurious throw pillows to add comfort and style to any space.',
        price: 45.0,
        originalPrice: 60.0,
        category: 'home',
        brand: 'Pottery Barn',
        images: [
          'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop',
          'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop&crop=entropy',
        ],
        rating: 4.3,
        reviewCount: 1245,
        colors: ['Blue', 'Gray', 'Green', 'Cream', 'Pink'],
        sizes: ['18x18 inches'],
        isInStock: true,
        isFeatured: false,
        isOnSale: true,
        discount: 25,
        material: 'Cotton Blend',
        features: ['Set of 2', 'Removable Covers', 'Machine Washable', 'Hidden Zipper'],
      ),
      Product(
        id: 'area_rug',
        name: 'Bohemian Area Rug',
        description: 'Beautiful bohemian-style area rug that adds warmth and character to any room.',
        price: 189.0,
        originalPrice: 249.0,
        category: 'home',
        brand: 'nuLOOM',
        images: [
          'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=600&h=600&fit=crop',
          'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=600&h=600&fit=crop&crop=entropy',
        ],
        rating: 4.4,
        reviewCount: 567,
        colors: ['Multi-Color', 'Blue/White', 'Red/Orange', 'Gray/Black'],
        sizes: ['5x8 ft', '8x10 ft', '9x12 ft'],
        isInStock: true,
        isFeatured: true,
        isOnSale: true,
        discount: 24,
        material: 'Polypropylene',
        features: ['Easy Clean', 'Fade Resistant', 'Low Pile', 'Non-Slip Backing'],
      ),

      // Sports
      Product(
        id: 'yoga_mat',
        name: 'Premium Yoga Mat',
        description: 'High-quality yoga mat with excellent grip and cushioning for all yoga practices.',
        price: 59.0,
        originalPrice: 79.0,
        category: 'sports',
        brand: 'Manduka',
        images: [
          'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&h=600&fit=crop',
          'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&h=600&fit=crop&crop=entropy',
        ],
        rating: 4.7,
        reviewCount: 1834,
        colors: ['Purple', 'Blue', 'Green', 'Pink', 'Black'],
        sizes: ['6mm Thick'],
        isInStock: true,
        isFeatured: true,
        isOnSale: true,
        discount: 25,
        material: 'Natural Rubber',
        features: ['Non-Slip Surface', 'Eco-Friendly', 'Lightweight', 'Carrying Strap'],
      ),
      Product(
        id: 'dumbbells',
        name: 'Adjustable Dumbbells',
        description: 'Space-saving adjustable dumbbells perfect for home workouts.',
        price: 299.0,
        originalPrice: 399.0,
        category: 'sports',
        brand: 'Bowflex',
        images: [
          'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&h=600&fit=crop',
          'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&h=600&fit=crop&crop=entropy',
        ],
        rating: 4.6,
        reviewCount: 923,
        colors: ['Black/Red'],
        sizes: ['5-50 lbs'],
        isInStock: true,
        isFeatured: true,
        isOnSale: true,
        discount: 25,
        material: 'Cast Iron',
        features: ['Quick Weight Change', 'Space Saving', 'Durable', 'Comfortable Grip'],
      ),
      Product(
        id: 'running_shoes',
        name: 'Running Shoes',
        description: 'Lightweight running shoes with advanced cushioning for maximum comfort.',
        price: 129.0,
        originalPrice: 159.0,
        category: 'sports',
        brand: 'Adidas',
        images: [
          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop',
          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop&crop=entropy',
        ],
        rating: 4.5,
        reviewCount: 1567,
        colors: ['Black/White', 'Blue/Orange', 'Gray/Red', 'All Black'],
        sizes: ['7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '12'],
        isInStock: true,
        isFeatured: false,
        isOnSale: true,
        discount: 19,
        material: 'Mesh and Synthetic',
        features: ['Boost Cushioning', 'Breathable Upper', 'Continental Rubber', 'Lightweight'],
      ),

      // Beauty
      Product(
        id: 'skincare_set',
        name: 'Complete Skincare Set',
        description: 'Complete 4-step skincare routine for healthy, glowing skin.',
        price: 89.0,
        originalPrice: 120.0,
        category: 'beauty',
        brand: 'CeraVe',
        images: [
          'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&h=600&fit=crop',
          'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&h=600&fit=crop&crop=entropy',
        ],
        rating: 4.6,
        reviewCount: 2156,
        colors: ['One Color'],
        sizes: ['Full Size'],
        isInStock: true,
        isFeatured: true,
        isOnSale: true,
        discount: 26,
        material: 'Skincare Products',
        features: ['4-Step Routine', 'All Skin Types', 'Dermatologist Tested', 'Fragrance Free'],
      ),
      Product(
        id: 'makeup_palette',
        name: 'Eyeshadow Palette',
        description: 'Professional eyeshadow palette with 20 highly pigmented shades.',
        price: 45.0,
        originalPrice: 65.0,
        category: 'beauty',
        brand: 'Urban Decay',
        images: [
          'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=600&h=600&fit=crop',
          'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=600&h=600&fit=crop&crop=entropy',
        ],
        rating: 4.8,
        reviewCount: 1342,
        colors: ['Neutral Tones', 'Smoky Tones', 'Colorful'],
        sizes: ['20 Shades'],
        isInStock: true,
        isFeatured: false,
        isOnSale: true,
        discount: 31,
        material: 'Pressed Powder',
        features: ['Highly Pigmented', 'Blendable', 'Long Lasting', 'Mirror Included'],
      ),

      // Books
      Product(
        id: 'programming_book',
        name: 'Clean Code: A Handbook',
        description: 'A comprehensive guide to writing clean, maintainable code.',
        price: 39.0,
        originalPrice: 49.0,
        category: 'books',
        brand: 'Prentice Hall',
        images: [
          'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600&h=600&fit=crop',
          'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600&h=600&fit=crop&crop=entropy',
        ],
        rating: 4.9,
        reviewCount: 3456,
        colors: ['One Color'],
        sizes: ['Paperback', 'Hardcover', 'Kindle'],
        isInStock: true,
        isFeatured: true,
        isOnSale: true,
        discount: 20,
        material: 'Paper',
        features: ['464 Pages', 'Educational', 'Programming Guide', 'Best Practices'],
      ),
      Product(
        id: 'cookbook',
        name: 'Mediterranean Cookbook',
        description: 'Discover the flavors of the Mediterranean with over 100 delicious recipes.',
        price: 24.0,
        originalPrice: 32.0,
        category: 'books',
        brand: 'Williams Sonoma',
        images: [
          'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&h=600&fit=crop',
          'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&h=600&fit=crop&crop=entropy',
        ],
        rating: 4.5,
        reviewCount: 876,
        colors: ['One Color'],
        sizes: ['Hardcover', 'Paperback'],
        isInStock: true,
        isFeatured: false,
        isOnSale: true,
        discount: 25,
        material: 'Paper',
        features: ['100+ Recipes', 'Color Photos', 'Healthy Eating', 'Easy Instructions'],
      ),

      // Toys & Games
      Product(
        id: 'building_blocks',
        name: 'Creative Building Blocks',
        description: 'Educational building blocks set that promotes creativity and learning.',
        price: 49.0,
        originalPrice: 69.0,
        category: 'toys',
        brand: 'LEGO',
        images: [
          'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=600&h=600&fit=crop',
          'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=600&h=600&fit=crop&crop=entropy',
        ],
        rating: 4.7,
        reviewCount: 1234,
        colors: ['Multi-Color'],
        sizes: ['500 Pieces'],
        isInStock: true,
        isFeatured: true,
        isOnSale: true,
        discount: 29,
        material: 'ABS Plastic',
        features: ['Educational', 'Creative Play', 'Safe Materials', 'Age 4+'],
      ),
      Product(
        id: 'board_game',
        name: 'Strategy Board Game',
        description: 'Engaging strategy board game perfect for family game nights.',
        price: 35.0,
        originalPrice: 45.0,
        category: 'toys',
        brand: 'Hasbro',
        images: [
          'https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?w=600&h=600&fit=crop',
          'https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?w=600&h=600&fit=crop&crop=entropy',
        ],
        rating: 4.4,
        reviewCount: 567,
        colors: ['One Color'],
        sizes: ['2-4 Players'],
        isInStock: true,
        isFeatured: false,
        isOnSale: true,
        discount: 22,
        material: 'Cardboard',
        features: ['2-4 Players', '60 Min Gameplay', 'Strategy Game', 'Age 10+'],
      ),

      // Automotive
      Product(
        id: 'car_charger',
        name: 'Fast Car Charger',
        description: 'Dual USB fast car charger compatible with all devices.',
        price: 19.0,
        originalPrice: 29.0,
        category: 'automotive',
        brand: 'Anker',
        images: [
          'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=600&h=600&fit=crop',
          'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=600&h=600&fit=crop&crop=entropy',
        ],
        rating: 4.3,
        reviewCount: 2234,
        colors: ['Black', 'White'],
        sizes: ['Dual USB'],
        isInStock: true,
        isFeatured: false,
        isOnSale: true,
        discount: 34,
        material: 'Aluminum Alloy',
        features: ['Fast Charging', 'Universal Compatible', 'LED Indicator', 'Compact Design'],
      ),
    ];
  }

  static List<Product> getFeaturedProducts() {
    return getAllProducts().where((product) => product.isFeatured).toList();
  }

  static List<Product> getProductsByCategory(String categoryId) {
    return getAllProducts().where((product) => product.category == categoryId).toList();
  }

  static List<Product> getOnSaleProducts() {
    return getAllProducts().where((product) => product.isOnSale).toList();
  }

  static Product? getProductById(String id) {
    try {
      return getAllProducts().firstWhere((product) => product.id == id);
    } catch (e) {
      return null;
    }
  }

  static List<Product> searchProducts(String query) {
    final lowercaseQuery = query.toLowerCase();
    return getAllProducts().where((product) {
      return product.name.toLowerCase().contains(lowercaseQuery) ||
             product.description.toLowerCase().contains(lowercaseQuery) ||
             product.brand.toLowerCase().contains(lowercaseQuery) ||
             product.category.toLowerCase().contains(lowercaseQuery);
    }).toList();
  }
}